name: Daily GitHub Trending (uv + pyproject)

on:
  schedule:
    # JST 09:00 = UTC 00:00
    - cron: "0 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: daily-trending
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.12"

      - name: Resolve & install deps
        run: uv sync

      - name: Run
        run: |
          uv run python trending.py \
            --language Python \
            --days 3 \
            --top 5 \
            --per-page 30 \
            --markdown-out out.md \
            --title "今日の“擬似”GitHubトレンド (Python)" \
            --slack

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trending-output
          path: |
            out.md
